import type { Metadata } from 'next';
import '@/styles/globals.scss';
import HeaderLayout from '@/libraries/layout/header.layout';

export const metadata: Metadata = {
  title: 'Easy Home',
  description: 'Generated by create next app'
};

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="grid grid-cols-5 gap-3 h-screen overflow-hidden">
        <HeaderLayout className="col-span-1" />
        <main className="col-span-4">{children}</main>
      </body>
    </html>
  );
}
